import { useState, type FormEvent } from "react";
import { ArrowUpRight, Check, Mail, MapPin, Mic2, UtensilsCrossed } from "lucide-react";

export default function MiamiInquiries() {
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <main className="miami-page miami-inquiries-page">
    <header className="miami-sub-header"><a className="miami-wordmark" href="/zakhybuildsai/portfolio/miami-trips-restaurants"><strong>MIAMI<span>✦</span></strong><small>TRIPS AND RESTAURANTS</small></a><nav><a href="/zakhybuildsai/portfolio/miami-trips-restaurants">HOME</a><a href="/zakhybuildsai/portfolio/miami-trips-restaurants/experiences">EPISODES &amp; EXPERIENCES</a><a className="is-active" href="/zakhybuildsai/portfolio/miami-trips-restaurants/inquiries">INQUIRIES</a></nav><a className="miami-header-cta" href="/zakhybuildsai/portfolio/miami-trips-restaurants/experiences">EXPLORE <ArrowUpRight /></a></header>
    <section className="miami-inquiry-hero"><div className="miami-shell"><p className="miami-eyebrow">INQUIRIES &amp; PARTNERSHIPS</p><h1>LET’S PLAN<br /><em>THE NEXT ONE.</em></h1><p>For restaurant collaborations, destination partnerships, podcast opportunities, hosted experiences, and media requests.</p></div></section>
    <section className="miami-inquiry-main"><div className="miami-shell miami-inquiry-layout"><aside className="miami-inquiry-side"><p className="miami-eyebrow">WAYS TO WORK TOGETHER</p><div><Mic2 /><h3>PODCAST &amp; MEDIA</h3><p>Guest conversations, episode partnerships, and video features.</p></div><div><UtensilsCrossed /><h3>RESTAURANTS</h3><p>Reviews, chef conversations, hosted dining, and launch moments.</p></div><div><MapPin /><h3>DESTINATIONS</h3><p>Travel campaigns, hotel stays, cultural guides, and city storytelling.</p></div><a href="mailto:hello@miamitripsandrestaurants.com"><Mail /> hello@miamitripsandrestaurants.com</a></aside>
      <div className="miami-inquiry-form-wrap">{submitted ? <div className="miami-form-success"><Check /><p className="miami-eyebrow">INQUIRY / DEMO</p><h2>WE’LL BE<br /><em>IN TOUCH.</em></h2><p>This is a visual portfolio demo. Your request was not sent or stored.</p><button type="button" className="miami-button" onClick={() => setSubmitted(false)}>RETURN TO FORM <ArrowUpRight /></button></div> : <form className="miami-inquiry-form" onSubmit={submit}><p className="miami-eyebrow">TELL US WHAT YOU’RE DREAMING UP</p><h2>START THE<br /><em>CONVERSATION.</em></h2><div className="miami-form-row"><label>NAME<input name="name" required placeholder="Your name" /></label><label>EMAIL<input name="email" required type="email" placeholder="you@email.com" /></label></div><div className="miami-form-row"><label>INQUIRY TYPE<select name="type" defaultValue="" required><option value="" disabled>Select one</option><option>Restaurant Partnership</option><option>Destination Partnership</option><option>Podcast / Media</option><option>Hosted Experience</option><option>General Inquiry</option></select></label><label>ESTIMATED BUDGET<select name="budget" defaultValue=""><option value="">Select a range</option><option>Under $2,500</option><option>$2,500–$5,000</option><option>$5,000–$10,000</option><option>$10,000+</option></select></label></div><label>OPPORTUNITY DETAILS<textarea name="details" rows={5} placeholder="Tell us about your restaurant, destination, campaign, or idea." /></label><button className="miami-button" type="submit">SEND DEMO INQUIRY <ArrowUpRight /></button><small>Portfolio demo only. This form does not send or store information.</small></form>}</div>
    </div></section>
  </main>;
}
