import { useState, type FormEvent } from "react";
import "./ralo-inquiries.css";

export default function RaloInquiriesPage() {
  const [submitted, setSubmitted] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <main className="ralo-inquiries-page">
    <header className="ralo-content-header"><a className="ralo-content-logo" href="/zakhybuildsai/portfolio/ralo" aria-label="Ralo home"><img src="/zakhy-assets/famgoon-header-logo-tight_138459fd.png" alt="FAMGOON" /></a><nav className={`ralo-content-nav ${menuOpen ? "ralo-content-nav--open" : ""}`} aria-label="Ralo navigation"><a href="/zakhybuildsai/portfolio/ralo" onClick={() => setMenuOpen(false)}>Home</a><a href="/zakhybuildsai/portfolio/ralo/content" onClick={() => setMenuOpen(false)}>Content &amp; Monetization</a><a className="is-active" href="/zakhybuildsai/portfolio/ralo/inquiries" onClick={() => setMenuOpen(false)}>Inquiries</a></nav><p className="ralo-content-label">RALO / FAMGOON</p><button className="ralo-content-menu" type="button" onClick={() => setMenuOpen((open) => !open)} aria-expanded={menuOpen} aria-label="Toggle Ralo navigation"><i /><i /></button></header>
    <section className="ralo-inquiry-hero"><div><p>Ralo / Inquiries</p><h1>Make a<br /><em>move.</em></h1><span>Shows. Features. Appearances. Collaborations.</span></div></section>
    <section className="ralo-inquiry-main"><div className="ralo-inquiry-side"><p>FAMGOON / REQUESTS</p><h2>Let’s put the right move in motion.</h2><div><span>01</span><b>Live performances</b></div><div><span>02</span><b>Features & collaborations</b></div><div><span>03</span><b>Appearances & events</b></div></div><div className="ralo-inquiry-form-wrap">{submitted ? <div className="ralo-inquiry-success"><p>RALO / REQUEST RECEIVED</p><h2>We got you.</h2><span>This is a visual portfolio demo. Nothing was sent or stored.</span><button type="button" onClick={() => setSubmitted(false)}>Return to form</button></div> : <form onSubmit={submit}><p>MAKE AN INQUIRY</p><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@email.com" /></label><label>Request type<select required defaultValue=""><option value="" disabled>Select one</option><option>Live performance</option><option>Feature</option><option>Collaboration</option><option>Appearance</option><option>Event</option></select></label><label>Details<textarea rows={5} placeholder="Tell us about the opportunity" /></label><button type="submit">Send demo inquiry <b>→</b></button><small>Portfolio demo only. This form does not send or store information.</small></form>}</div></section>
  </main>;
}
